name: cd

on:
    push:
      branches: [main]

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest

        steps:
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: "1.20"
                
            - name: Check out code
              uses: actions/checkout@v3

            - name: Run script
              run: ./scripts/buildprod.sh

            - id: 'auth'
              uses: 'google-github-actions/auth@v1'
              with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'
        
            - name: 'Build and push Docker image'
              run: 'gcloud builds submit --tag europe-west3-docker.pkg.dev/notely-403320/notely-ar-repo/notely:latest .'

            - name: 'Deploy to Cloud Run'
              run: gcloud run deploy notely --image europe-west3-docker.pkg.dev/notely-403320/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-403320 --max-instances=4
            